<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- <OutputPath>..\artifacts\</OutputPath> -->
    <AssemblyTitle>GiftModels</AssemblyTitle>
    <Description>Models which can be used to represents gifts</Description>
    <Company>UC Davis</Company>
    <Product>GiftModels</Product>
    <Copyright>Copyright © 2014</Copyright>
    <AssemblyVersion>2.0.0.*</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JsModels.Net" Version="2.0.38" PrivateAssets="none"
      IncludeAssets="runtime; build" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="jsmodels-license.txt" Pack="true" PackagePath="content/" />
  </ItemGroup>
  <PropertyGroup>
    <GenerateJsModels>true</GenerateJsModels>
    <JsModelsClasses>
      GiftDetails,DonorContainer,DonorDetail,Distribution,Pledge,AllocationDetail,PaymentContainer,Attachment,FinancialDetails,PremiumDetails,KfsDetails,Affiliate,Acknowledgement
    </JsModelsClasses>
  </PropertyGroup>
</Project>