using System;

namespace GiftModels
{
    public class PaymentContainer
    {
        public string Source { get; set; }
        public string SourceId { get; set; }
        public string Type { get; set; }
        public decimal Amount { get; set; }
        
        /// <summary>
        /// Authorization or Acceptance Datetime
        /// </summary>
        public virtual DateTime? AuthorizedAt { get; set; }

        #region Check Properties
        public string CheckNumber { get; set; }
        #endregion

        #region Credit Card Properties
        /// <summary>
        /// 3 digit card type code (ex: visa == 001)
        /// </summary>
        public virtual string CardType { get; set; }

        /// <summary>
        /// Masked or Suffix of Account. May contain 'x's
        /// </summary>
        public virtual string CardNumber { get; set; }

        /// <summary>
        /// MM-YYYY
        /// </summary>
        public virtual DateTime? CardExpiration { get; set; }

        /// <summary>
        /// Short Reply Code returned by processor (Chase/Visa/Etc) authorizing payment
        /// </summary>
        public virtual string CardAuthorizationCode { get; set; }

        /// <summary>
        /// CyberSource Transaction Id
        /// Generated by CyberSource
        /// </summary>
        public virtual string CardTransactionId { get; set; }

        /// <summary>
        /// Payment Processor (Chase/Visa/Etc) Transaction Id
        /// Generated by Processor, passed through from CyberSource
        /// </summary>
        public virtual string CardTransactionReferenceNumber { get; set; }
        #endregion
    }
}